import jsPDF from 'jspdf';

const PINK = [236, 72, 153];
const GRAY = [107, 114, 128];
const WHITE = [255, 255, 255];
const DARK = [31, 41, 55];

function addHeader(doc, title, pageNum, totalPages) {
  doc.setFillColor(...PINK);
  doc.rect(0, 0, 220, 28, 'F');
  doc.setTextColor(...WHITE);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 18);
  doc.setFontSize(9);
  doc.text(`Page ${pageNum} of ${totalPages}`, 196, 18, { align: 'right' });
  doc.setTextColor(...DARK);
}

function addFooter(doc) {
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text('Generated by Plan My Party Pal | PlanMyPartyPal.com', 105, 287, { align: 'center' });
}

export function generatePartyPDF(partyData, checklist, mergedZones, excludedItems, zoneChecks, timeline) {
  const doc = new jsPDF();
  const totalPages = 4;
  let y = 0;

  // PAGE 1 — Cover
  addHeader(doc, `${partyData.childName}'s ${partyData.theme} Party`, 1, totalPages);
  addFooter(doc);
  y = 40;
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PINK);
  doc.text('Party Planning Kit', 105, y, { align: 'center' });
  y += 15;
  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.text(`A ${partyData.theme} Themed Birthday Party`, 105, y, { align: 'center' });
  y += 20;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const info = [
    ['Birthday Star', partyData.childName],
    ['Age', partyData.age],
    ['Date', partyData.date || 'TBD'],
    ['Venue', partyData.venueType || 'TBD'],
    ['Guests', partyData.guestCount],
    ['Budget', `$${partyData.budget}`],
    ['Activities', (partyData.selectedActivities || []).join(', ') || 'TBD'],
  ];
  info.forEach(([label, val]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 40, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(val), 90, y);
    y += 8;
  });

  // PAGE 2 — Checklist by Zone
  doc.addPage();
  addHeader(doc, 'Party Checklist by Zone', 2, totalPages);
  addFooter(doc);
  y = 36;

  if (mergedZones && mergedZones.length > 0) {
    mergedZones.forEach(zone => {
      const activeItems = zone.allItems.filter(item => {
        const key = item._type === 'zone' ? item._zoneKey : `checklist-${item._checklistIdx}`;
        return !(excludedItems && excludedItems[key]);
      });
      if (!activeItems.length) return;

      if (y > 260) { doc.addPage(); addHeader(doc, 'Party Checklist (cont.)', 2, totalPages); addFooter(doc); y = 36; }
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...PINK);
      doc.text(`${zone.emoji} ${zone.name}`, 14, y);
      y += 6;
      doc.setTextColor(...DARK);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);

      activeItems.forEach(item => {
        if (y > 270) { doc.addPage(); addHeader(doc, 'Party Checklist (cont.)', 2, totalPages); addFooter(doc); y = 36; }
        const isChecked = item._type === 'zone' ? (zoneChecks && zoneChecks[item._zoneKey]) : item.completed;
        const checkbox = isChecked ? '[x]' : '[ ]';
        const cost = item.estimatedCost ? ` (${item.estimatedCost})` : '';
        const line = `${checkbox} ${item.task}${cost}`;
        const lines = doc.splitTextToSize(line, 175);
        doc.text(lines, 20, y);
        y += lines.length * 4.5;
      });
      y += 4;
    });
  }

  // PAGE 3 — Timeline
  doc.addPage();
  addHeader(doc, 'Day-of Timeline', 3, totalPages);
  addFooter(doc);
  y = 40;
  doc.setFontSize(10);

  const timelineItems = timeline && timeline.length > 0 ? timeline : [
    { time: '2:00 PM', event: 'Guests Arrive & Free Play', duration: '30 min' },
    { time: '2:30 PM', event: 'Activities & Games', duration: '45 min' },
    { time: '3:15 PM', event: 'Snacks & Drinks', duration: '15 min' },
    { time: '3:30 PM', event: 'Main Event', duration: '30 min' },
    { time: '4:00 PM', event: 'Cake & Happy Birthday', duration: '20 min' },
    { time: '4:20 PM', event: 'Open Presents', duration: '20 min' },
    { time: '4:40 PM', event: 'Party Favors & Goodbye', duration: '20 min' },
  ];

  timelineItems.forEach(item => {
    doc.setFont('helvetica', 'bold');
    doc.text(item.time || '', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(item.event || '', 55, y);
    doc.setTextColor(...GRAY);
    doc.text(item.duration || '', 170, y);
    doc.setTextColor(...DARK);
    y += 8;
  });

  // PAGE 4 — Notes
  doc.addPage();
  addHeader(doc, 'Notes & Reminders', 4, totalPages);
  addFooter(doc);
  y = 40;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  for (let i = 0; i < 25; i++) {
    doc.setDrawColor(200, 200, 200);
    doc.line(14, y, 196, y);
    y += 9;
  }

  return doc;
}

export function downloadPartyPDF(partyData, checklist, mergedZones, excludedItems, zoneChecks, timeline) {
  const doc = generatePartyPDF(partyData, checklist, mergedZones, excludedItems, zoneChecks, timeline);
  doc.save(`${partyData.childName || 'Party'}-Planning-Kit.pdf`);
}

export function generateSamplePDF() {
  const sampleData = {
    childName: 'Vinny',
    age: '8',
    date: '2025-03-15',
    budget: '400',
    guestCount: '15',
    location: 'Orlando, FL',
    theme: 'Star Wars',
    venueType: 'Backyard',
    selectedActivities: ['Nerf Gun Battle', 'Obstacle Course', 'Freeze Dance'],
  };

  const sampleChecklist = [
    { category: 'Decorations', task: 'Star Wars balloons and banner', priority: 'high', estimatedCost: '$15-25', completed: false },
    { category: 'Decorations', task: 'Lightsaber centerpieces', priority: 'medium', estimatedCost: '$10-20', completed: false },
    { category: 'Activity Supplies', task: 'Nerf guns (15 count)', priority: 'high', estimatedCost: '$40-60', completed: false },
    { category: 'Activity Supplies', task: 'Nerf darts bulk pack', priority: 'high', estimatedCost: '$15-20', completed: false },
    { category: 'Activity Supplies', task: 'Safety goggles (15 count)', priority: 'high', estimatedCost: '$20-30', completed: false },
    { category: 'Food & Cake', task: 'Star Wars themed cake', priority: 'high', estimatedCost: '$35-50', completed: false },
    { category: 'Food & Cake', task: 'Pizza and snacks for 15', priority: 'high', estimatedCost: '$40-60', completed: false },
    { category: 'Party Favors', task: 'Mini lightsaber goodie bags', priority: 'medium', estimatedCost: '$20-30', completed: false },
  ];

  const sampleTimeline = [
    { time: '2:00 PM', event: 'Jedi Padawans Arrive', duration: '30 min' },
    { time: '2:30 PM', event: 'Nerf Gun Battle Royale', duration: '45 min' },
    { time: '3:15 PM', event: 'Obstacle Course Challenge', duration: '20 min' },
    { time: '3:35 PM', event: 'Freeze Dance (Star Wars Music)', duration: '15 min' },
    { time: '3:50 PM', event: 'Refuel at the Cantina (Snacks)', duration: '15 min' },
    { time: '4:05 PM', event: 'Birthday Cake & Song', duration: '15 min' },
    { time: '4:20 PM', event: 'Open Presents', duration: '20 min' },
    { time: '4:40 PM', event: 'Party Favors & Farewell', duration: '20 min' },
  ];

  const doc = generatePartyPDF(sampleData, sampleChecklist, null, {}, {}, sampleTimeline);
  doc.save('Vinnys-Star-Wars-Party-Kit.pdf');
}
